apiVersion: v1
kind: Service
metadata:
  name: hashresponse-svc
  labels:
    app.kubernetes.io/name: "hashresponse"
    app.kubernetes.io/version: "1.9"
spec:
  type: ClusterIP
  selector:
    app: hashresponse
  ports:
    - name: http
      port: 2345
      targetPort: 8090
      protocol: TCP
