apiVersion: apps/v1
kind: Deployment
metadata:
  name: the-project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: the-project
  template:
    metadata:
      labels:
        app: the-project
    spec:
      volumes:
        - name: the-project-image
          persistentVolumeClaim:
            claimName: the-project-claim
      containers:
        - name: image-finder
          image: ghcr.io/timokramer/image-finder:1.12
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
              name: finder-http
          volumeMounts:
          - name: the-project-image
            mountPath: /usr/src/app/files
        - name: image-response
          image: ghcr.io/timokramer/image-response:1.12
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
              name: response-http
          volumeMounts: # Mount volume
          - name: the-project-image
            mountPath: /usr/src/app/files
