apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: persisting-data-ingress
spec:
  rules:
  - http:
      paths:
      - path: /pong
        pathType: Prefix
        backend:
          service:
            name: persisting-data-svc
            port:
              number: 2345
      - path: /log-output
        pathType: Prefix
        backend:
          service:
            name: persisting-data-svc
            port:
              number: 2346
