apiVersion: v1
kind: Service
metadata:
  name: persisting-data-svc
  labels:
    app.kubernetes.io/name: "persisting-data"
    app.kubernetes.io/version: "1.11"
spec:
  type: ClusterIP
  selector:
    app: persisting-data
  ports:
    - name: pong
      port: 2345
      targetPort: 8090
      protocol: TCP
    - name: log-output
      port: 2346
      targetPort: 8091
      protocol: TCP
