apiVersion: apps/v1
kind: Deployment
metadata:
  name: images-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: images
  template:
    metadata:
      labels:
        app: images
    spec:
      volumes: # Define volume
        - name: shared-image
          emptyDir: {}
      containers:
        - name: image-finder
          image: ghcr.io/timokramer/image-finder:1.10
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
              name: finder-http
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/files
        - name: image-response
          image: ghcr.io/timokramer/image-response:1.10
          imagePullPolicy: Always
          ports:
            - containerPort: 8091
              name: response-http
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/files
