apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: images-ingress
spec:
  rules:
  - http:
      paths:
      - path: /finder
        pathType: Prefix
        backend:
          service:
            name: images-svc
            port:
              number: 2345
      - path: /response
        pathType: Prefix
        backend:
          service:
            name: images-svc
            port:
              number: 2346
