apiVersion: v1
kind: Service
metadata:
  name: images-svc
spec:
  type: ClusterIP
  selector:
    app: images
  ports:
    - name: finder
      port: 2345
      protocol: TCP
      targetPort: 8090
    - name: response
      port: 2346
      protocol: TCP
      targetPort: 8091
