apiVersion: v1
kind: Service
metadata:
  name: pong-app-svc
  labels:
    app.kubernetes.io/name: "pong-app"
    app.kubernetes.io/version: "1.9"
spec:
  type: ClusterIP
  selector:
    app: pong-app
  ports:
    - name: http
      port: 2346
      targetPort: 8090
      protocol: TCP
