apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  labels:
    app.kubernetes.io/name: "log-output"
    app.kubernetes.io/version: "1.7"
spec:
  type: ClusterIP
  selector:
    app: log-output
  ports:
    - name: http
      port: 2345
      targetPort: 8090
      protocol: TCP
