apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
  labels:
    app.kubernetes.io/name: "todo-app"
    app.kubernetes.io/version: "1.8"
spec:
  type: ClusterIP
  selector:
    app: todo-app
  ports:
    - name: http
      port: 2345
      targetPort: 8090
      protocol: TCP
