apiVersion: v1
kind: Service
metadata:
  name: hashresponse-svc
  labels:
    app.kubernetes.io/name: "hashresponse"
    app.kubernetes.io/version: "1.5"
spec:
  type: NodePort
  selector:
    app: hashresponse
  ports:
    - name: http
      nodePort: 30080
      port: 1234
      targetPort: 8090
      protocol: TCP
