apiVersion: v1
kind: Service
metadata:
  name: hash-response-svc
  labels:
    app.kubernetes.io/name: "hash-response"
    app.kubernetes.io/version: "1.5"
spec:
  type: ClusterIP
  selector:
    app: hash-response
  ports:
    - port: 80
      targetPort: 8090
      protocol: TCP
